export const lists = [
  { name: 'กระเจี๊ยบแก้วถุงฟอยล์', image: '/img/list/กระเจี๊ยบแก้วถุงฟอยล์.png', description: 'ราคาส่ง : 28 บาท', price: 35, category: ['ผลไม้แปรรูป'] },
  { name: 'กระเจี๊ยบแก้วโบว์แดง', image: '/img/list/กระเจี๊ยบแก้วโบว์แดง.png', description: 'ราคาส่ง : 28 บาท', price: 35, category: ['ผลไม้แปรรูป'] },
  { name: 'กระเจี๊ยบแก้วมือจับ', image: '/img/list/กระเจี๊ยบแก้วมือจับ.png', description: 'ราคาส่ง : 28 บาท', price: 35, category: ['ผลไม้แปรรูป'] },
  { name: 'กล้วยกวนถุงฟอยล์', image: '/img/list/กล้วยกวนถุงฟอยล์.png', description: 'ราคาส่ง : 28 บาท', price: 35, category: ['ผลไม้แปรรูป'] },
  { name: 'กล้วยกวนโบว์แดง', image: '/img/list/กล้วยกวนโบว์แดง.png', description: 'ราคาส่ง : 28 บาท', price: 35, category: ['ผลไม้แปรรูป'] },
  { name: 'กล้วยกวนมือจับ', image: '/img/list/กล้วยกวนมือจับ.png', description: 'ราคาส่ง : 28 บาท', price: 35, category: ['ผลไม้แปรรูป'] },
  { name: 'กล้วยตากอบน้ำผึ้งกล่องกระดาษ', image: '/img/list/กล้วยตากอบน้ำผึ้งกล่องกระดาษ.png', description: 'ราคาส่ง : 28 บาท', price: 35, category: ['ผลไม้แปรรูป'] },
  { name: 'กล้วยตากอบน้ำผึ้งกล่องพลาสติก', image: '/img/list/กล้วยตากอบน้ำผึ้งกล่องพลาสติก.png', description: 'ราคาส่ง : 28 บาท', price: 35, category: ['ผลไม้แปรรูป'] },
  { name: 'กล้วยน้ำว้าทอดปรุงเนยถุงฟอยล์', image: '/img/list/กล้วยน้ำว้าทอดปรุงเนยถุงฟอยล์.png', description: 'ราคาส่ง : 28 บาท', price: 35, category: ['ผลไม้แปรรูป', 'ของทอด'] },
  { name: 'กล้วยน้ำว้าทอดปรุงเนยมือจับ', image: '/img/list/กล้วยน้ำว้าทอดปรุงเนยมือจับ.png', description: 'ราคาส่ง : 28 บาท', price: 35, category: ['ผลไม้แปรรูป', 'ของทอด'] },
  { name: 'กล้วยแผ่นอบม้วน', image: '/img/list/กล้วยแผ่นอบม้วน.png', description: 'ราคาส่ง : 28 บาท', price: 35, category: ['ผลไม้แปรรูป'] },
  { name: 'กล้วยเล็บมือนางอบแห้ง', image: '/img/list/กล้วยเล็บมือนางอบแห้ง.png', description: 'ราคาส่ง : 28 บาท', price: 35, category: ['ผลไม้แปรรูป'] },
  { name: 'เกาลัดกอหย่วน', image: '/img/list/เกาลัดกอหย่วน.png', description: 'ราคาส่ง : 28 บาท', price: 35, category: ['ผลไม้แปรรูป'] },
  { name: 'ขนมไข่กรอบมือจับ', image: '/img/list/ขนมไข่กรอบมือจับ.png', description: 'ราคาส่ง : 28 บาท', price: 35, category: ['ของทอด'] },
  { name: 'ขนมปี๊บขาไก่ 5 รส', image: '/img/list/ขนมปี๊บขาไก่5รส.png', description: 'ราคาส่ง : - บาท', price: 169, category: ['ขนมปี๊ป', 'ของทอด'] },
  { name: 'ขนมปี๊บขาไก่รสเค็ม', image: '/img/list/ขนมปี๊บขาไก่รสเค็ม.png', description: 'ราคาส่ง : - บาท', price: 169, category: ['ขนมปี๊ป', 'ของทอด'] },
  { name: 'ขนมปี๊บคุกกี้ครีมขาว', image: '/img/list/ขนมปี๊บคุกกี้ครีมขาว.png', description: 'ราคาส่ง : - บาท', price: 169, category: ['ขนมปี๊ป', 'ของหวาน'] },
  { name: 'ขนมปี๊บคุกกี้ช็อควนิลา', image: '/img/list/ขนมปี๊บคุกกี้ช็อควนิลา.png', description: 'ราคาส่ง : - บาท', price: 169, category: ['ขนมปี๊ป', 'ของหวาน'] },
  { name: 'ขนมปี๊บคุกกี้ทุเรียน', image: '/img/list/ขนมปี๊บคุกกี้ทุเรียน.png', description: 'ราคาส่ง : - บาท', price: 169, category: ['ขนมปี๊ป', 'ของหวาน'] },
  { name: 'ขนมปี๊บคุกกี้ใบเตย', image: '/img/list/ขนมปี๊บคุกกี้ใบเตย.png', description: 'ราคาส่ง : - บาท', price: 169, category: ['ขนมปี๊ป', 'ของหวาน'] },
  { name: 'ขนมปี๊บคุกกี้สตรอเบอร์รี่', image: '/img/list/ขนมปี๊บคุกกี้สตรอเบอร์รี่.png', description: 'ราคาส่ง : - บาท', price: 169, category: ['ขนมปี๊ป', 'ของหวาน'] },
  { name: 'ขนมปี๊บงาทอง', image: '/img/list/ขนมปี๊บงาทอง.png', description: 'ราคาส่ง : - บาท', price: 169, category: ['ขนมปี๊ป'] },
  { name: 'ขนมปี๊บจักรเล็กสับปะรด', image: '/img/list/ขนมปี๊บจักรเล็กสับปะรด.png', description: 'ราคาส่ง : - บาท', price: 169, category: ['ขนมปี๊ป', 'ของหวาน'] },
  { name: 'ขนมปี๊บแบล็คแอนด์ไวท์', image: '/img/list/ขนมปี๊บแบล็คแอนด์ไวท์.png', description: 'ราคาส่ง : - บาท', price: 169, category: ['ขนมปี๊ป', 'ของหวาน'] },
  { name: 'ขนมปี๊บวีโอช็อคดำ', image: '/img/list/ขนมปี๊บวีโอช็อคดำ.png', description: 'ราคาส่ง : - บาท', price: 169, category: ['ขนมปี๊ป', 'ของหวาน'] },
  { name: 'ขนมปี๊บเวเฟอร์แผ่นโยเกิร์ตส้ม', image: '/img/list/ขนมปี๊บเวเฟอร์แผ่นโยเกิร์ตส้ม.png', description: 'ราคาส่ง : - บาท', price: 169, category: ['ขนมปี๊ป', 'ของหวาน'] },
  { name: 'ขนมปี๊บเวเฟอร์แผ่นรสช็อกโกแลต', image: '/img/list/ขนมปี๊บเวเฟอร์แผ่นรสช็อกโกแลต.png', description: 'ราคาส่ง : - บาท', price: 169, category: ['ขนมปี๊ป', 'ของหวาน'] },
  { name: 'ขนมปี๊บหมีช็อกโก้', image: '/img/list/ขนมปี๊บหมีช็อกโก้.png', description: 'ราคาส่ง : - บาท', price: 169, category: ['ขนมปี๊ป', 'ของหวาน'] },
  { name: 'ขนุนอบกรอบถุงฟอยล์', image: '/img/list/ขนุนอบกรอบถุงฟอยล์.png', description: 'ราคาส่ง : 28 บาท', price: 35, category: ['ผลไม้แปรรูป', 'ของทอด'] },
  { name: 'ข้าวเกรียบปลาหมึกมือจับ', image: '/img/list/ข้าวเกรียบปลาหมึกมือจับ.png', description: 'ราคาส่ง : 28 บาท', price: 35, category: ['ของทอด'] },
  { name: 'คุกกี้งาดำ', image: '/img/list/คุกกี้งาดำ.png', description: 'ราคาส่ง : 28 บาท', price: 35, category: ['ของหวาน'] },
  { name: 'คุกกี้สิงคโปร์', image: '/img/list/คุกกี้สิงคโปร์.png', description: 'ราคาส่ง : 28 บาท', price: 35, category: ['ของหวาน'] },
  { name: 'เค้กไต้หวัน', image: '/img/list/เค้กไต้หวัน.png', description: 'ราคาส่ง : 28 บาท', price: 35, category: ['ของหวาน'] },
  { name: 'ปลาหวานแผ่น', image: '/img/list/ปลาหวานแผ่น.png', description: 'ราคาส่ง : 28 บาท', price: 35, category: ['ผลไม้แปรรูป'] },
  { name: 'ปลาหวานเส้น', image: '/img/list/ปลาหวานเส้น.png', description: 'ราคาส่ง : 28 บาท', price: 35, category: ['ผลไม้แปรรูป'] },
  { name: 'ผัดหมี่โคราช', image: '/img/list/ผัดหมี่โคราช.png', description: 'ราคาส่ง : 28 บาท', price: 35, category: ['ผลไม้แปรรูป'] },
  { name: 'เวเฟอร์สติ๊ก(โอโจ้)', image: '/img/list/เวเฟอร์สติ๊ก(โอโจ้).png', description: 'ราคาส่ง : 28 บาท', price: 35, category: ['ของหวาน'] },
  { name: 'หมี่กรอบรสต้มยำ', image: '/img/list/หมี่กรอบรสต้มยำ.png', description: 'ราคาส่ง : - บาท', price: 40, category: ['ของทอด'] },
  { name: 'หมี่กรอบสูตรดั้งเดิม', image: '/img/list/หมี่กรอบสูตรดั้งเดิม.png', description: 'ราคาส่ง : - บาท', price: 40, category: ['ของทอด'] },
  { name: 'หมี่กรอบสูตรสมุนไพร', image: '/img/list/หมี่กรอบสูตรสมุนไพร.png', description: 'ราคาส่ง : - บาท', price: 40, category: ['ของทอด'] },
  { name: 'อินทผลัม', image: '/img/list/อินทผลัม.png', description: 'ราคาส่ง : 28 บาท', price: 35, category: ['ผลไม้แปรรูป'] },
]