export const lists = [
  { name: 'กล้วยกวนถุงฟอยล์', image: '/img/list/กล้วยกวนถุงฟอยล์.png', description: 'ราคาส่ง : 28 บาท', price: 35, category: ['ผลไม้แปรรูป'] },
  { name: 'กล้วยกวนโบว์แดง', image: '/img/list/กล้วยกวนโบว์แดง.png', description: 'ราคาส่ง : 28 บาท', price: 35, category: ['ผลไม้แปรรูป'] },
  { name: 'กล้วยกวนมือจับ', image: '/img/list/กล้วยกวนมือจับ.png', description: 'ราคาส่ง : 28 บาท', price: 35, category: ['ผลไม้แปรรูป'] },
  { name: 'กล้วยตากอบน้ำผึ้งกล่องกระดาษ', image: '/img/list/กล้วยตากอบน้ำผึ้งกล่องกระดาษ.png', description: 'ราคาส่ง : 28 บาท', price: 35, category: ['ผลไม้แปรรูป'] },
  { name: 'กล้วยตากอบน้ำผึ้งกล่องพลาสติก', image: '/img/list/กล้วยตากอบน้ำผึ้งกล่องพลาสติก.png', description: 'ราคาส่ง : 28 บาท', price: 35, category: ['ผลไม้แปรรูป'] },
  { name: 'กล้วยน้ำว้าทอดปรุงเนยถุงฟอยล์', image: '/img/list/กล้วยน้ำว้าทอดปรุงเนยถุงฟอยล์.png', description: 'ราคาส่ง : 28 บาท', price: 35, category: ['ผลไม้แปรรูป', 'ของทอด'] },
  { name: 'กล้วยน้ำว้าทอดปรุงเนยมือจับ', image: '/img/list/กล้วยน้ำว้าทอดปรุงเนยมือจับ.png', description: 'ราคาส่ง : 28 บาท', price: 35, category: ['ผลไม้แปรรูป', 'ของทอด'] },
  { name: 'กล้วยแผ่นอบม้วน', image: '/img/list/กล้วยแผ่นอบม้วน.png', description: 'ราคาส่ง : 28 บาท', price: 35, category: ['ผลไม้แปรรูป'] },
  { name: 'กล้วยเล็บมือนางอบแห้ง', image: '/img/list/กล้วยเล็บมือนางอบแห้ง.png', description: 'ราคาส่ง : 28 บาท', price: 35, category: ['ผลไม้แปรรูป'] },
  { name: 'ขนมไข่กรอบมือจับ', image: '/img/list/ขนมไข่กรอบมือจับ.png', description: 'ราคาส่ง : 28 บาท', price: 35, category: ['ของทอด'] },
  { name: 'ขนุนอบกรอบถุงฟอยล์', image: '/img/list/ขนุนอบกรอบถุงฟอยล์.png', description: 'ราคาส่ง : 28 บาท', price: 35, category: ['ผลไม้แปรรูป','ของทอด'] },
  { name: 'ข้าวเกรียบปลาหมึกมือจับ', image: '/img/list/ข้าวเกรียบปลาหมึกมือจับ.png', description: 'ราคาส่ง : 28 บาท', price: 35, category: ['ของทอด'] },
  { name: 'คุกกี้สิงคโปร์', image: '/img/list/คุกกี้สิงคโปร์.png', description: 'ราคาส่ง : 28 บาท', price: 35, category: ['ของหวาน'] },
  { name: 'เค้กไต้หวัน', image: '/img/list/เค้กไต้หวัน.png', description: 'ราคาส่ง : 28 บาท', price: 35, category: ['ของหวาน'] },
  { name: 'ปลาหวานแผ่น', image: '/img/list/ปลาหวานแผ่น.png', description: 'ราคาส่ง : 28 บาท', price: 35, category: ['ผลไม้แปรรูป'] },
  { name: 'ปลาหวานเส้น', image: '/img/list/ปลาหวานเส้น.png', description: 'ราคาส่ง : 28 บาท', price: 35, category: ['ผลไม้แปรรูป'] },
  { name: 'ผัดหมี่โคราช', image: '/img/list/ผัดหมี่โคราช.png', description: 'ราคาส่ง : 28 บาท', price: 35, category: ['ผลไม้แปรรูป'] },
  { name: 'เวเฟอร์สติ๊ก(โอโจ้)', image: '/img/list/เวเฟอร์สติ๊ก(โอโจ้).png', description: 'ราคาส่ง : 28 บาท', price: 35, category: ['ของหวาน'] },
  { name: 'อินทผลัม', image: '/img/list/อินทผลัม.png', description: 'ราคาส่ง : 28 บาท', price: 35, category: ['ผลไม้แปรรูป'] },
]
